"""add language field to posts model

Revision ID: 81147119b67b
Revises: a50f70ea6055
Create Date: 2018-04-24 16:28:23.301879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81147119b67b'
down_revision = 'a50f70ea6055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'language')
    # ### end Alembic commands ###
